---
title: "Métodos de Amostragem na PNADc"
Author: "Miguel Conforto"
output: html_notebook
---
# Por que utilizar amostras?
<div style="text-align: justify">
  Como verificar a quantididade de tempero em um prato que está sendo preparado? como detectar problemas de saúde através de um exame de sangue? todas essas questões podem ser respondidas analisando uma amostra, ou seja, uma parte que é capaz de explicar o todo.
<br/>   A escolha por uma pesquisa amostral não é diferente: responder temas sobre a população geral a partir de pequenas amostras. Esse metódo possibilita uma pesquisa efetiva com resultados precisos e um orçamento reduzido quando comparado a um censo, por exemplo. O orçamento é tão viável que permite à pesquisa tomar caráter contínuo, como é o caso da PNADc.
<br/>   A questão da continuidade, no caso da PNAD, exige que a cada trimestre uma nova amostra seja sorteada para coleta, caso contrário a pesquisa se tornaria um acompanhamento de um conjunto fixo de domicílios. Mas como é feito esse sorteio de domicílios?


# Como é realizada a amostragem na PNADc?

<div style="text-align: justify">
  A escolha da amostra segue os princípios de uma Amostra Aleatória Simples (AAS), oque significa que cada domicílio tem a mesma chance de ser sorteado para participar da pesquisa. Contudo, como garantir que um domicílio do interior do Amazonas terá a mesma chance de ser sorteado que um domicílio do centro de São Paulo?
<br/>   Para assegurar a conscistência da amostra quanto a chance de escolha de cada domicílio, o IBGE separa cada região do Brasil em pequenos estratos de tal forma que, dentro de cada estrato, os domicílios tenham a mesma chance de serem sorteados para a amostra.
<br/>   Vamos imaginar que o conjunto universo U represente todos os domicílios do Brasil.

$$\mathcal{U}= \left\{1,\ 2,\ ...,\ N\right\}$$

  Onde N é o n-ésimo e último domicílio do Brasil. Como nem todos os elementos de U têm a mesma chance de serem sorteados para participar da amostra é preciso particionar o conjunto U em subconjuntos com chances iguais entre os elementos.


$$\mathcal U_1,\ \mathcal U_2,\ ...,\ \mathcal U_h$$

  Esses subconjuntos são chamados de estratos de U e não precisam ter o mesmo número de elementos em cada estrato, contudo eles devem obedecer as seguintes regras:


$$\mathcal U\ =\ \bigcup_ {h=1}^H\ \mathcal U_h \quad e \quad \mathcal U_h\ \bigcap\ \mathcal U_{h'}\ =\  \emptyset$$

  Isso significa que cada estrato deve conter domicílios diferentes entre si e que a união de todos os estratos deve ser igual ao total de domicílio, ou seja, o conjunto U.
<br/>  Além disso, cada domicílio presente nos estratos tem diversas características de interese para a pesquisa, como por exemplo a renda percapita, o número de quartos, as condições de ocupação e muitos outros. Sendo assim, é possível olhar para cada característica distinta de um estrato da seguinte forma:


$$D\ =\ (Y_{11},\ ...,\ Y_{1N_1},\ ...,\ Y_{hi},\ ...,\ Y_{HN_H})$$


  Com D sendo o vetor de características do Domicílio e Y a característica de interesse. Os índices em cada elemento Y são referentes ao estrato e domicílio que ele pertence, ou seja, no caso to estrato 1 tem-se as características para todos os N  domicílios contidos nele da seguinte forma:
  
$$Y_{11},\ Y_{12},\ ...,\ Y_{1N_1} $$
  Então, caso Y estivesse se referindo a renda dos domicílios desse estratos, seria possível calcular a renda média nesse estrato e esta seria feita da maneira convencional na estatística.
  
$$\mu_h\ =\ \frac{1}{N_h}\ \sum_{i=1}^{N_h}\ Y_{hi}\ : \quad Média\; do\; estrato\; h$$
  O mesmo é válido para o cálculo da variância no estrato
  
$$\sigma^2\ =\ \frac{1}{N_h} \sum_{i=1}^{N_h}\ (Y_{hi}\ -\ \mu_h)\ ^2\ : \quad Variância\; do\; estrato\; h $$
 Entretanto, essas contas retornam apenas informações sobre cada estrato enquanto a PNADc retorna informações em diferentes níveis de mensuração. Como é feita a análise para todos os estratos então? e após analisar os estratos, como é possível inferir algo sobre a população a partir da amostra?
  
# Inferindo resultados a partir da amostra

<div style="text-align: justify">
  Agora que todos os domicílios foram divididos em estratos e têm a mesma probabilidade de serem sorteados, é possível selecionar uma Amostra Aleatória Simples dentro de cada estrato e realizar contas como média e variância. Mas como calcular a média e variância entre estratos diferentes em que cada domicílio tem uma probabilidade diferente de ser sorteado? Para resolver esse problema é preciso tomar conhecimento de algumas relações entre os estratos.

$$N\ =\ \sum_{h=1}^{H} N_h\ : Tamanho\; do\; universo\; (\mathcal U) \\e\\ W_h\ =\ \frac{N_h}{N}\ :\ Peso\; (proporção)\; do\; estrato\; h,\; com \;\sum_{h=1}^{H}W_h\ =\ 1$$
  A partir do peso do estrato é possível calcular a média entre estratos diferentes e obter a média populacional (global), de modo que esta seja a média ponderada dos estratos.
  
$$\mu\ =\ \sum_{h=1}^{H} W_h\ \mu_h\ : \quad Média\; populacional$$
  Por conta disso a PNADc disponibiliza em seus microdados o peso do domicílio, peso da pessoa e peso da família. Dessa forma se torna viável resumir os dados em tabelas com o nível de mensuração que for desejado, seja ele municipal, Regional ou do Brasil inteiro.
<br/>  Contudo, ainda é preciso tomar mais um cuidado com relação à amostras. Como já foi citado antes, o objetivo das amostras é obter informações sobre o todo conhecendo apenas uma parte dele, para chegar a esse resultado temos que usar os estimadores.
<br/>  Um estimador busca representar um parâmetro populacional da forma mais verossimelhante possível, para reduzir eventuais erros estatísticos os estimadores são calculados de uma forma diferente. As fórmulas mostradas até agora dizem respeito ao caso em que os dados são da população, como um censo, e não da amostra. Veremos os principais estimadores paara resumir oa dados em tabelas.
<br/>  A estimação do total populacional é dada por:
  
$$T_{es}\ =\ \sum_{h=1}^{H} N_h\ {\mu}_h $$
  O estimador para a média populacional

$$\overline{\mathcal y}_{es}\ =\ \sum_{h=1}^{H}W_h\ \mu_h $$
  Até então o cálculo para os estimadores não foge do escopo visto anteriormente, o único que mudará consideravelmente será o estimador para variância populacional:

$$\mathcal S^2\ =\ \frac{1}{N-1} \sum_{h=1}^{H}\sum_{i=1}^{N_h}\ (Y_{hi}\ -\ \overline y_{es})^2 $$
  Sabendo disso, fica evidente o porquê um estudo sobre amostragem se faz necessário para gerar tabelas da PNADc a partir dos microdados. Como muitos profissionais que não vêm da área de exatas usualmente precisam fazer relatórios com esses dados, é importante lhes dar a possibilidade de criar suas próprias tabelas sem demandar um profundo conhecimento sobre programação e estatística.
<br/>  Foi com esse intuito que o Projeto de Tabulação de dados da PNADc foi criado, visando facilitar o acesso aos resultados da PNAD para pesquisadores de todas as áreas e a criação de tabelas de forma rápida e eficaz.